### ISSUE TITLE
Dialyzer errors

### ISSUE THREAD

**Issue by lasseebert** [certifi/erlang-certifi#12]
Not sure if this is the right place.

I have an Elixir application that depends on certifi. After updating to 1.1.0 I get a warning when dialyzer creates the PLTs:

```
:dialyzer.run error: Could not get abstract code for file: /vagrant/legolas/_build/dev/lib/certifi/ebin/certifi.beam (please recompile it with +debug_info)
```

**Comment by zachdaniel** [comment]
:+1: We're having the same issue.

**Comment by lasseebert** [comment]
https://github.com/certifi/erlang-certifi/pull/7 seems to have caused it. Reverting that PR fixes the dialyzer errors I get.

**Comment by benoitc** [comment]
this will be fixed today with a new release. sorry for the delay

**Comment by lasseebert** [comment]
Awesome :)

**Comment by lasseebert** [comment]
Ah, didn't see https://github.com/certifi/erlang-certifi/pull/13 before now.

**Comment by benoitc** [comment]
fixed in latest master. by default it is compiled with `debug_info`. This setting can be overridden in rebar.config using the `overrides` feature if needed. 

@ericmj i removed the files from priv. Also now only one large beam is created by default. I removed the weakcert one as  it is not really needed neither encouraged to use.

**Comment by lasseebert** [comment]
Thanks :)
